Add tutorial notebook for public released object catalog
LSSTDESC/DC2-Public-Release pull request #1
Opened 2021-01-04 16:58 UTC by yymao

This PR adds a tutorial notebook for public released object catalog. For this notebook to run, one needs to get GCR v0.9.2 and also gcr-catalogs master + LSSTDESC/gcr-catalogs#523 + LSSTDESC/gcr-catalogs#524. 

The notebook can use some polish and maybe a few more science examples. I am opening this PR now so that people can make suggestions (esp. since Slack is down right now). 

I will open another PR for the tutorial notebook for public released truth-match catalog.

2021-01-05 17:04 UTC, yymao commented
Just a note for potential reviewers: you should have access to `~yymao/desc` on NERSC if you are in the DESC, so by running the first cell,

```python
import sys
sys.path.insert(0, "/global/homes/y/yymao/desc/generic-catalog-reader")
sys.path.insert(0, "/global/homes/y/yymao/desc/gcr-catalogs/")
```

you'll get all the needed dependencies, and you don't need to grab GCR and GCRCatalogs PRs on your own. Hopefully this will encourage people to review this notebook. 

BTW, those who review this notebook may also want to review https://github.com/LSSTDESC/gcr-catalogs/pull/523, a PR that introduces some helper functions for the purpose of this notebook.

2021-01-05 17:53 UTC, fjaviersanchez requested changes
Sorry, I missed this yesterday. I think that the notebook looks good. There are a few typos but the plots and code look good and relevant to me. 

As a stylistic suggestion: Maybe I would add a phrase towards the end to say that it's the end of the notebook: "Finally, we show a practical example to illustrate how to access the dataset and perform a specific selection. We have `extendedness`...". In any case, please feel free to disregard this last suggestion.

2021-01-05 17:53 UTC, fjaviersanchez commented on notebooks/object_table_gcrcatalogs_intro.ipynb
> +    "which is an effort made by the Rubin to standardize the format of the official Data Release Products (DRP).\n",
the Rubin to standardize... To me it looks like jargon, maybe change to "the Rubin commmunity". Or maybe project, observatory, or scientific collaborations?

2021-01-05 17:53 UTC, fjaviersanchez commented on notebooks/object_table_gcrcatalogs_intro.ipynb
> +    "The DC2 DR6 is a very large data set; loading the full object table into memory is usually not feasible. To access the data in a memory efficient fashion while maintain reasonable performace, we
I think `while maintain` would be `while maintaining`

2021-01-05 17:53 UTC, fjaviersanchez commented on notebooks/object_table_gcrcatalogs_intro.ipynb
> +    "Becuase the physical data files are in Parquet format, loading specific columns (1) is efficient and does not require reading in the full table. \n",
Becuase -> because

2021-01-05 17:53 UTC, fjaviersanchez commented on notebooks/object_table_gcrcatalogs_intro.ipynb
> +    "The physical data files are also partitioned in \"tracts\", each of which corresponds to a region of the sky (see Figure 1 of the release note); hence, loading only a subset of \"tracts\" or ite
`iterate` -> `iterating`

2021-01-05 17:53 UTC, fjaviersanchez commented on notebooks/object_table_gcrcatalogs_intro.ipynb
> +    "Finally, subsampling the table at random can make your analysis calculation faster and use less memory, but it does not save much in term of I/O as all the rows need to be read in before subsamp
I would leave either calculation or analysis and take the other out.

2021-01-05 17:53 UTC, fjaviersanchez commented on notebooks/object_table_gcrcatalogs_intro.ipynb
> +    "You will use `get_quantities` to retrive the data, and there are several convient, high-level features that help you achieve the three measures described above. When calling `get_quantities`, yo
`retrive` -> `retrieve`

2021-01-05 17:53 UTC, fjaviersanchez commented on notebooks/object_table_gcrcatalogs_intro.ipynb
> +    "You will use `get_quantities` to retrive the data, and there are several convient, high-level features that help you achieve the three measures described above. When calling `get_quantities`, yo
`convient` -> `convenient`

2021-01-05 17:53 UTC, fjaviersanchez commented on notebooks/object_table_gcrcatalogs_intro.ipynb
> +    "Each query should be a string that contains a *simple* python expression, in which the variables are column names. \n",
Maybe include a link to an explanation of what a simple python expression is.

2021-01-05 17:53 UTC, fjaviersanchez commented on notebooks/object_table_gcrcatalogs_intro.ipynb
> +    "Each query should be a string that contains a *simple* python expression, in which the variables are column names. \n",
https://docs.python.org/3/reference/simple_stmts.html

2021-01-05 17:53 UTC, fjaviersanchez commented on notebooks/object_table_gcrcatalogs_intro.ipynb
> +    "* Other useful quantities: `blendedness`, measure of how flux is affected by neighbors: (1 - flux.child/flux.parent) (see 4.9.11 of [Bosch et al. 2018](http://adsabs.harvard.edu/abs/2018PASJ...7
Maybe say that more details on `extendedness` are later in the notebook?

2021-01-05 19:28 UTC, yymao commented on notebooks/object_table_gcrcatalogs_intro.ipynb
> +    "which is an effort made by the Rubin to standardize the format of the official Data Release Products (DRP).\n",
Should be "Rubin Observatory". Fixed.

2021-01-05 19:29 UTC, yymao commented on notebooks/object_table_gcrcatalogs_intro.ipynb
> +    "Each query should be a string that contains a *simple* python expression, in which the variables are column names. \n",
Instead I added a reference to [numexpr doc](https://numexpr.readthedocs.io/en/latest/user_guide.html#supported-operators) for supported operators and functions, since that's what GCRQuery actually uses.

2021-01-05 19:30 UTC, yymao commented on notebooks/object_table_gcrcatalogs_intro.ipynb
> +    "* Other useful quantities: `blendedness`, measure of how flux is affected by neighbors: (1 - flux.child/flux.parent) (see 4.9.11 of [Bosch et al. 2018](http://adsabs.harvard.edu/abs/2018PASJ...7
I've added the reference for `extendedness`, since we also gave the reference to `blendedness` here too.

2021-01-05 19:31 UTC, yymao commented
Thanks, @fjaviersanchez. I've fixed the typos and implemented your suggestions. 

I'll also leave this PR open for a bit in case others have further comments. Similarly we need to remove/update the custom paths in the PR when the download portol is set up.

2021-01-05 19:39 UTC, fjaviersanchez approved these changes
Thanks!

2021-01-05 22:12 UTC, rmandelb reviewed
Hi Yao.  Thanks, this is super useful!  I was wondering if it might be worth incorporating a plot showing number counts as a function of magnitude? (I know you have the color plot, but i thought showing that the counts do what you'd expect as a function of magnitude when you select galaxies might be of interest to users - kind of like in https://github.com/LSSTDESC/DC2-analysis/blob/master/contributed/Run_1.2_exploration.ipynb though there we also had truth catalogs, which I realize is not part of this notebook.  At least when I'm playing with a new dataset I consider that a key plot...)

2021-01-05 22:12 UTC, rmandelb commented on notebooks/object_table_gcrcatalogs_intro.ipynb
> +    "The definitions, units, and types of these fields is documented in the data release note (Table 1).\n",
```suggestion
    "The definitions, units, and types of these fields are documented in the data release note (Table 1).\n",
```

2021-01-05 22:12 UTC, rmandelb commented on notebooks/object_table_gcrcatalogs_intro.ipynb
> +    "As explained in the note, the values exposed here are not the native columns produced by the Data Management stack.\n",
```suggestion
    "As explained in the note, the values exposed here are not the native columns produced by the LSST Science Pipelines.\n",
```

2021-01-05 22:12 UTC, rmandelb commented on notebooks/object_table_gcrcatalogs_intro.ipynb
> +    "* Quality flags: e.g, does the source have any interpolated pixels? Has any of the measurement algorithms returned an error?\n",
```suggestion
    "* Quality flags: e.g, does the source have any interpolated pixels? Has any measurement algorithm returned an error?\n",
```
or
```suggestion
    "* Quality flags: e.g, does the source have any interpolated pixels? Have any of the measurement algorithms returned an error?\n",
```

2021-01-05 22:12 UTC, rmandelb commented on notebooks/object_table_gcrcatalogs_intro.ipynb
> +    "tract_filter(4225)  # select one tract, 4225\n",
At some point it might be useful to mention how the user can get a list of all available tracts?

2021-01-05 22:12 UTC, rmandelb commented on notebooks/object_table_gcrcatalogs_intro.ipynb
> +    "For now, we have `extendedness` as a tool for star/galaxy classification. An object is considered extended if the the difference between the `PSF` magnitude and the [`CModel` magnitude](https://
```suggestion
    "For now, we have `extendedness` as a tool for star/galaxy classification. An object is considered extended if the the difference between the `PSF` magnitude and the [`CModel` magnitude](https://www.sdss.org/dr12/algorithms/magnitudes/#cmodel) is above a certain threshold (0.0164). To learn more about this see [Bosch et al. 2018](http://adsabs.harvard.edu/abs/2018PASJ...70S...5B) section 4.9.10.\n",
```

2021-01-05 22:12 UTC, rmandelb commented on notebooks/object_table_gcrcatalogs_intro.ipynb
> +    "* Other useful quantities: `blendedness`, measure of how flux is affected by neighbors: (1 - flux.child/flux.parent) (see 4.9.11 of [Bosch et al. 2018](http://adsabs.harvard.edu/abs/2018PASJ...7
```suggestion
    "* Other useful quantities: `blendedness`, measure of how flux is affected by neighbors: (1 - flux.child/flux.parent) (see section 4.9.11 of [Bosch et al. 2018](http://adsabs.harvard.edu/abs/2018PASJ...70S...5B)); `extendedness`, classifies sources as extended or point source (see section 4.9.10 of [Bosch et al. 2018](http://adsabs.harvard.edu/abs/2018PASJ...70S...5B))."
```

2021-01-06 01:29 UTC, yymao commented
Thanks @rmandelb --- in addition to the typo/wording fixes which I just accepted your suggestions, I've also added how to find out available tracts and the example of making a galaxy number density plot (mostly stole from your notebook).

2021-01-06 01:42 UTC, rmandelb commented
Thanks!  I think this notebook will be super useful.

2021-01-07 22:56 UTC, merged